POST {{host}}/user/create
Content-Type: application/json


{
  "username": "henri",
  "password": "henri",
  "email" : "sedhjodev@gmail.com"
}

###

GET {{host}}/user/activate/5c18a21c0cd59f0ee44a6310

###

DELETE {{host}}/user/delete/14jkkltest

###

