POST {{host}}/account/create
Content-Type: application/json
Authorization: Bearer 9cc98d64-1a7c-4778-b0e5-989a060bd1de


{
  "username": "herve",
  "password": "herve",
  "email" : "sedhjodev@gmail.com"
}

###


